---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
name: "pgrwl"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
      # postgres
      - containerPort: 30265
        hostPort: 30265
        protocol: TCP
      # distroless
      - containerPort: 30266
        hostPort: 30266
        protocol: TCP
